const sequelize = require('../config/connection');
const { Hauskeepr } = require('../models');

const hauskeeprdata = [{
        username: 'anghiari',
        email: 'anghiari123456@gmail.com',
        password: 'p@55w0rd',
        first_name: 'leonardo',
        last_name: 'da vinci',
        date_of_birth: '02/23/1800',
        address_line_1: '80 Strada Anchiano',
        address_line_2: 'Milan',
        city: 'Vinci',
        zip_code: '82335',
        state: 'HI',
        profession_id: 3,
        hourly_rate: 19.75
    },
    {
        username: 'ursula',
        email: 'ursula@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Ursula',
        last_name: 'Seawitch',
        date_of_birth: '08/17/1882',
        address_line_1: '111 Dark Cave',
        address_line_2: '',
        city: 'Under The Sea',
        zip_code: '00345',
        state: 'HI',
        profession_id: 3,
        hourly_rate: 12.75
    },
    {
        username: 'sebastian',
        email: 'anghiari1800@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Sebastian',
        last_name: 'Crab',
        date_of_birth: '08/17/1882',
        address_line_1: '10 Ocean Dr',
        address_line_2: '',
        city: 'Ocean City',
        zip_code: '00345',
        state: 'HI',
        profession_id: 1,
        hourly_rate: 16.75
    },
    {
        username: 'ariel',
        email: 'ariel@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Ariel',
        last_name: 'Mermaid',
        date_of_birth: '08/17/1882',
        address_line_1: '11 Ocean Dr',
        address_line_2: '',
        city: 'Ocean City',
        zip_code: '00345',
        state: 'HI',
        profession_id: 1,
        hourly_rate: 16.75
    },
    {
        username: 'erik',
        email: 'Erik@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Erik',
        last_name: 'Prince',
        date_of_birth: '08/17/1882',
        address_line_1: '11 Swanky Castle',
        address_line_2: '',
        city: 'Above The Sea',
        zip_code: '00345',
        state: 'HI',
        profession_id: 1,
        hourly_rate: 7.75
    },
    {
        username: 'sursha',
        email: 'soairse@gmail.com ',
        password: 'password',
        first_name: 'Soairse',
        last_name: 'Ronan',
        date_of_birth: '09/17/1992',
        address_line_1: '11 Irish Cave',
        address_line_2: 'Lower Level',
        city: 'Wales',
        zip_code: '98245',
        state: 'HI',
        profession_id: 2,
        hourly_rate: 7.75
    },
    {
        username: 'angelina',
        email: 'angelina@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Angelina',
        last_name: 'Jolie',
        date_of_birth: '06/12/2000',
        address_line_1: '10 Unbroken Blvd',
        address_line_2: 'Underground Level',
        city: 'Oahu',
        zip_code: '11345',
        state: 'HI',
        profession_id: 4,
        hourly_rate: 8.75
    },
    {
        username: 'phillip',
        email: 'phillip@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Phillip',
        last_name: 'Shire',
        date_of_birth: '01/17/1800',
        address_line_1: '89 Recon St',
        address_line_2: '',
        city: 'Miami',
        zip_code: '00335',
        state: 'HI',
        profession_id: 5,
        hourly_rate: 7.75
    },
    {
        username: 'virginia',
        email: 'virginia@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Virginia',
        last_name: 'Woolfe',
        date_of_birth: '05/12/1892',
        address_line_1: '13 Dalloway Street',
        address_line_2: 'Apt 4',
        city: 'Honolulu',
        zip_code: '11345',
        state: 'HI',
        profession_id: 6,
        hourly_rate: 10.75
    },
    {
        username: 'dumbo',
        email: 'dumbo@gmail.com',
        password: 'p@55w0rd',
        first_name: 'Dumbo',
        last_name: 'Stewart',
        date_of_birth: '01/23/1990',
        address_line_1: '80 PT Barnum Avenue',
        address_line_2: 'Tent 456',
        city: 'Kauai',
        zip_code: '22335',
        state: 'HI',
        profession_id: 3,
        hourly_rate: 12.75
    }
];

const seedHauskeeprs = () => Hauskeepr.bulkCreate(hauskeeprdata, { individualHooks: true });

module.exports = seedHauskeeprs;